# Generated by Django 5.0.3 on 2024-05-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signupdata_remove_todoitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
